### PR TITLE
Cleanup, fix SUBFOLDER env var

### PR DESCRIPTION
**Pull request by davepgreene**
This PR does the following:
1. Adds eslint and an eslint config to the repo.
2. Fixes linting and stylistic issues in the codebase.
3. Refactors some common functions and configuration options into a more standard file structure.
4. Added a more standard config object for credentials. This will require changes [here](https://github.com/linuxserver/docker-boinc/blob/master/root/etc/cont-init.d/50-config#L12), [here](https://github.com/linuxserver/docker-calibre/blob/master/root/etc/cont-init.d/50-config#L10) and anywhere else that consumes this package.
5. Added unit tests.
6. **Most importantly:** 
    * Fixes an issue where if a `SUBFOLDER` env var is provided, the websocket server that `guacamole-lite` spawns listens on the wrong path and will never receive the [`websocat` call](https://github.com/linuxserver/docker-baseimage-rdesktop-web/blob/master/root/etc/services.d/autostart/run#L23) used to autostart the application .
    * Fixes an issue where if a `SUBFOLDER` env var is provided, the Express server that gclient spawns listens on the wrong path.

Because gclient is running in Docker, it's ok to hardcode the path that the router listens on because we specify a `SUBFOLDER` in order to ensure that static resources can load with a proxy configuration.

If you'd prefer additional changes, or tests just let me know. I have this hacked up in a local image and it's working great but I'm sure there are upstream consumers of this package that I'm unaware of and/or a desire for this to be a stable replacement for the previous (but heavyweight) guacamole war-based baseimage.

### CODE REVIEW

**Comment by davepgreene** [comment]
In order to consume this upstream in [linuxserver/docker-calibre](https://github.com/linuxserver/docker-calibre), the `sed` pattern [here](https://github.com/linuxserver/docker-calibre/blob/master/root/etc/cont-init.d/50-config#L10) will need to be updated. I assume there are other consumers that use gclient in a similar way so it would be useful to know what other images use gclient.

**Comment by thelamer** [comment]
This is a serious refactor, thanks for all the work. 
I just came back from a long AFK, basically the story with this app is it is not written in a method that you would consider proper.
It uses no known frameworks outside of jquery for simple rendering in of stuff and I statically host the libs in repo minified. Not to mention it has no real standard for formatting testing etc. It was written by a system administrator with no previous dev experience at the time years ago (me).
Refactoring this into something like React or Vue and its alts is on a long list of stuff I need to catch up on.

When I get time I will put this through it's paces.

**Comment by davepgreene** [comment]
I'm not a frontend guy so I'm not sure how much I could help with refactoring the UI but I'll help out if you need it. Hopefully the testing and linting stuff I've put into place in this PR will be helpful moving forward if/when you decide to do a UI refactor.

Assuming you're in agreement on the approach of this PR, I think the most helpful next step would be to determine who gclient's consumers are and open PRs there to  ensure that they're properly modifying the `config.json` file and replacing those `sed` commands.

If not, let me know what you'd like to see here and I'll refactor as necessary.

**Comment by thelamer** [comment]
I hate to do this especially after all this time, but I just refactored the app a bunch. 
Essentially I spun up your fork and started playing with it and while I was at it started realizing a ton of things I wrote a long time ago that did not make any sense, so I started re-writing all of it including a baked in file manager. 

The settings file while a good idea does not fit with how we use this app in a docker container, we need all the variables to be processed as environment vars. 
The token generator code is essentially only used in special situations to be able to use websocat to fire up a non used session, so I expect that code to just sit there as long as it can do basically that. 

The automated testing stuff is cool, but as you can see from this project's history we are not ingesting 100s of commits. Essentially every time there is a major change the loop testing will be to spin up a https://github.com/linuxserver/docker-webtop and ensure it functions as it should, which also certifies our other desktop containers. 

I think there is potential in having an alternative piece of software outside of the stock JAVA guacamole client as a project that can be ingested by anyone maybe written in a more modern framework like React or Vue, but for our use as an organization to wrap desktop apps in Docker containers this project will always be hyper focused on that use case. 

I also think you have the skills to spin up and maintain a project of that scope looking over this code.

**Pull request closed without merging**
